= AS-C User Documentation

== Introduction

The second release of this application bridges the gap between a text-mining pipeline using the AlvisNLP/ML platform and the parent application Florilège.


Named-entity recognition and relation prediction has been applied on a corpus about __Bacteria__ and the resulting data has been integrated into the Florilège application. These annotations can be queried using a __beta__ version of the Florilèg application. The annotations can be accessed from the Florilège interface, as well as from the standalone search engine of the first release (available at http://bibliome.jouy.inra.fr/demo/seedev/alvisir/webapi/search?).


== Data Processing Scenarios

In AS-C, we have outlined the following data processing scenarios:

* <<application_design.adoc#, Application design>> (corpus building, resources gathering, etc.)
* <<production_processing.adoc#, Production processing>> (automatic annotation of a corpus by a text-mining pipeline and integration of the results into a parent application)
* <<resource_update.adoc#, Resource update>> (corpus increment, external resource update)

The application of this second release (Florilège) is part of the "Production processing" scenario and is fully documented <<parent-application.adoc#, here>>. From the parent application, the user has the possibility to access the semantic search engine of the first release, which is fully documented <<web_app_doc.adoc#, here>>. Florilège as well as the semantic search engine provide an easier access to information about microbial biodiversity from the scientific literature.  
