= Production processing

== Automatic annotation of a corpus

The AS-C text-mining pipeline automatically extracts the following entities:

* Microbial taxa (normalized according to the NCBI taxonomy)

* Microbial habitats (normalized according to the OntoBiotope ontology)

* Microbial phenotypes (normalized according to the OntoBiotope ontology)

* Relationships between taxa and their habitats ("lives_in" relation)

== Integration into a parent application

The text-mining annotations have been integrated into the parent application Florilège enabling a researcher to search and cross taxa, habitats and phenotypes of bacteria.

Moreover, the same annotations are indexed by the semantic search engine of the first release and can be accessed directly, through the search interface available at http://bibliome.jouy.inra.fr/demo/pubmed-ontobiotope/alvisir/webapi/search?.


Detailed documentation, including a tutorial guiding the user on the interface can be found in the <<parent-application#, Florilège documentation>>.

Detailed documentation on how to use the search engine can be found in the <<web_app_doc.adoc#, AS-C web application documentation>>.















